# Generated by Django 5.0.6 on 2025-05-13 08:28

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(default=core.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(default=core.models.generate_random_food_id, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(default=core.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('vendor_type', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('id_card', models.FileField(blank=True, null=True, upload_to='vendor_ids/')),
                ('approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('event_id', models.CharField(default=core.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_start_time', models.TimeField(blank=True, null=True)),
                ('event_end_time', models.TimeField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_size', models.CharField(blank=True, max_length=50, null=True)),
                ('event_package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_details', models.TextField(blank=True, null=True)),
                ('addons', models.TextField(blank=True, null=True)),
                ('guest_list', models.TextField(blank=True, null=True)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('addon_food_items', models.ManyToManyField(blank=True, related_name='event_registrations', to='core.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='InvitedGuest',
            fields=[
                ('guest_id', models.CharField(default=core.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('guest_type', models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'VIP'), ('VVIP', 'VVIP'), ('With Family', 'With Family')], max_length=20)),
                ('max_accompanying', models.PositiveIntegerField(default=0)),
                ('invitation_send_status', models.IntegerField(default=0)),
                ('invitation_accept_status', models.IntegerField(default=0)),
                ('accepted_members', models.PositiveIntegerField(default=0)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventregistration')),
            ],
        ),
    ]
