# Generated by Django 5.0.6 on 2025-05-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitedguest',
            name='max_accompanying',
        ),
        migrations.AddField(
            model_name='invitedguest',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitedguest',
            name='max_companions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invitedguest',
            name='monetarygifts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invitedguest',
            name='primary_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='core.invitedguest'),
        ),
        migrations.AlterField(
            model_name='invitedguest',
            name='accepted_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitedguest',
            name='guest_type',
            field=models.CharField(max_length=50),
        ),
    ]
