# Generated by Django 5.0.6 on 2025-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_invitedguest_max_accompanying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedguest',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitedguest',
            name='relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
