# Generated by Django 5.0.6 on 2025-05-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitedguest_age_invitedguest_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitedguest',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
