# Generated by Django 5.0.6 on 2025-05-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventregistration_payment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonetaryGift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='core.eventregistration')),
            ],
        ),
    ]
