# Generated by Django 5.0.6 on 2025-05-17 20:03

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_monetarygift'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('order_id', models.CharField(default=core.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('service', 'Service'), ('addon', 'Add-On')], max_length=10)),
                ('accepted', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addon_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fooditem')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='core.eventregistration')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.vendor')),
            ],
            options={
                'unique_together': {('event', 'vendor', 'addon_food')},
            },
        ),
    ]
